### PR TITLE
Removed Dashboard page and added Loading icon for Login

### PR DESCRIPTION
**Pull request by tiaanicolee**

### CODE REVIEW

**Comment by tiaanicolee** [comment]
I tried to do separate pull requests, but they all got squished together. The changes are supposed to remove the dashboard page, add the loading icon for logging in, and there is a the Mars logo on the Welcome page. If we're not happy with the logo placement, then I will happily change it. :)
screen shot 2017-05-08 at 10 47 56 am

**Comment by baldwinjj** [comment]
Hmmm would it look funny if we put it to the left of the text?

**Comment by tiaanicolee** [comment]
screen shot 2017-05-09 at 2 40 30 pm
like this? or next to all lines of the text and keeping the centering of the text?

**Comment by baldwinjj** [comment]
Hmmm I don't really like it there but I really couldn't tell you where else. Do you have any ideas?

**Comment by baldwinjj** [comment]
If it was to the side like that, I think you'd want it to be the height of all of the text and you'd want the text to be right justified.

**Pull request merged**
